# -*- coding: utf-8 -*-
"""ex2-es_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iqvqsszgEsHDuAUsAM-Y2QAvZ6PbINv1
"""

# STEP 1: SETUP & VOCABULARY
import torch
import torch.nn.functional as F
import random
import requests

# read in all the Spanish surnames
url = "https://raw.githubusercontent.com/luizoquadros-lang/NLP_Surnames_predict/main/apellidos_es.txt"
response = requests.get(url)
words = response.text.splitlines()

print(f"Total words: {len(words)}")
print(words[:10])

# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
vocab_size = len(itos)
print(f"Dynamic vocabulary size: {vocab_size}")
print(itos)

# STEP 2: DATASET SPLIT (TRAIN / DEV / TEST)
random.seed(42)
random.shuffle(words)

block_size = 4 # context length

def build_dataset(words_list):
    X, Y = [], []
    for w in words_list:
        context = [0] * block_size
        for ch in w + '.':
            ix = stoi[ch]
            X.append(context)
            Y.append(ix)
            context = context[1:] + [ix] # crop and append
    return torch.tensor(X), torch.tensor(Y)

# split data: 80% train, 10% dev, 10% test
n1 = int(0.8 * len(words))
n2 = int(0.9 * len(words))

Xtr, Ytr = build_dataset(words[:n1])
Xdev, Ydev = build_dataset(words[n1:n2])
Xte, Yte = build_dataset(words[n2:])

print(f"Training set size: {Xtr.shape[0]} examples")
print(f"Dev set size: {Xdev.shape[0]} examples")
print(f"Test set size: {Xte.shape[0]} examples")

# STEP 3: MODEL INITIALIZATION
# optimal hyperparameters to prevent overfitting
emb_dim = 12
hidden_dim = 100

g = torch.Generator().manual_seed(2147483647)
C = torch.randn((vocab_size, emb_dim), generator=g)
W1 = torch.randn((block_size * emb_dim, hidden_dim), generator=g)
b1 = torch.randn(hidden_dim, generator=g)
W2 = torch.randn((hidden_dim, vocab_size), generator=g)
b2 = torch.randn(vocab_size, generator=g)

parameters = [C, W1, b1, W2, b2]
for p in parameters:
    p.requires_grad = True

print(f"Total model parameters: {sum(p.nelement() for p in parameters)}")

# STEP 4: TRAINING LOOP
steps = 200000
batch_size = 32
lossi = []

print("Starting training...")
for i in range(steps):
    # minibatch construct
    ix = torch.randint(0, Xtr.shape[0], (batch_size,), generator=g)

    # forward pass
    emb = C[Xtr[ix]] # (32, 4, 10)
    h = torch.tanh(emb.view(-1, block_size * emb_dim) @ W1 + b1) # (32, 100)
    logits = h @ W2 + b2 # (32, 35)
    loss = F.cross_entropy(logits, Ytr[ix])
    # print(loss.item())

    # backward pass
    for p in parameters:
        p.grad = None
    loss.backward()

    # update
    #lr = lrs[i]
    lr = 0.1 if i < 100000 else 0.01
    for p in parameters:
        p.data -= lr * p.grad

    # track stats
    lossi.append(loss.log10().item())
    if i % 20000 == 0:
        print(f"Step {i:7d}/{steps} | Minibatch Loss: {loss.item():.4f}")

print("Training completed!")

# STEP 5: QUALITY EVALUATION
@torch.no_grad()
def split_loss(split_name, X, Y):
    emb = C[X]
    h = torch.tanh(emb.view(-1, block_size * emb_dim) @ W1 + b1)
    logits = h @ W2 + b2
    loss = F.cross_entropy(logits, Y)
    print(f"Final {split_name} Loss: {loss.item():.4f}")

print("=== FINAL MODEL EVALUATION ===")
split_loss('Train', Xtr, Ytr)
split_loss('Dev  ', Xdev, Ydev)
split_loss('Test ', Xte, Yte)

# STEP 6: GENERATE SAMPLE NAMES
g = torch.Generator().manual_seed(2147483647 + 10)

print("=== Generated Spanish Surnames ===")
for _ in range(30):
    out = []
    context = [0] * block_size
    while True:
      emb = C[torch.tensor([context])]
      h = torch.tanh(emb.view(1, -1) @ W1 + b1)
      logits = h @ W2 + b2
      probs = F.softmax(logits, dim=1)
      ix = torch.multinomial(probs, num_samples=1, generator=g).item()
      context = context[1:] + [ix]
      out.append(ix)
      if ix == 0:
        break

    print(''.join(itos[i] for i in out[:-1]))

# STEP 7: CROSS-LINGUAL EVALUATION (ES Model - PT Data)

# loading the Portuguese dataset
words_pt = requests.get("https://raw.githubusercontent.com/luizoquadros-lang/NLP_Surnames_predict/main/sobrenomes_pt_br.txt").text.splitlines()
print(f"Loaded {len(words_pt)} Portuguese names.")

# evaluate loss on Portuguese data
X_pt, Y_pt = [], []
skipped_pt = 0

for w in words_pt:
    # skip names with Portuguese specific characters (ã, ç, etc.) that the Spanish model has never seen
    if any(ch not in stoi for ch in w):
        skipped_pt += 1
        continue

    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X_pt.append(context)
        Y_pt.append(ix)
        context = context[1:] + [ix]

X_pt = torch.tensor(X_pt)
Y_pt = torch.tensor(Y_pt)

with torch.no_grad():
    emb = C[X_pt]
    h = torch.tanh(emb.view(-1, block_size * emb.shape[2] if len(emb.shape)==3 else block_size * C.shape[1]) @ W1 + b1)
    logits = h @ W2 + b2
    loss_es_on_pt = F.cross_entropy(logits, Y_pt)

print(f"\n=== EVALUATION RESULTS ===")
print(f"Spanish Model Loss on PT Data: {loss_es_on_pt.item():.4f}")
print(f"(Evaluated on {X_pt.shape[0]} character transitions. Skipped {skipped_pt} names due to out-of-vocabulary characters.)")

# generate Portuguese names to see the transfer quality
print("\n=== GENERATION: Spanish Model trying to generate Portuguese names ===")
g_sample = torch.Generator().manual_seed(2147483647 + 100)

for _ in range(40):
    out = []
    context = [0] * block_size
    while True:
        emb = C[torch.tensor([context])]
        h = torch.tanh(emb.view(1, -1) @ W1 + b1)
        logits = h @ W2 + b2
        probs = F.softmax(logits, dim=1)
        ix = torch.multinomial(probs, num_samples=1, generator=g_sample).item()
        context = context[1:] + [ix]
        out.append(ix)
        if ix == 0:
            break
    print(''.join(itos[i] for i in out[:-1]))