# -*- coding: utf-8 -*-
"""ex2-pt_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zzd-D_gJnxra7xnKAi_Su1-S_uEQ3203

Portuguese Character-level model
"""

# STEP 1: SETUP & VOCABULARY
import requests

# read in all the portuguese surnames
url = "https://raw.githubusercontent.com/luizoquadros-lang/NLP_Surnames_predict/main/sobrenomes_pt_br.txt"
response = requests.get(url)
words = response.text.splitlines()

# we found there are 5010 words, no problem, we just remove the last 10
words = words[:-10]

print(f"Total words: {len(words)}")
print(f"Examples: {words[:10]}")

# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
vocab_size = len(itos)

print(f"Dynamic vocabulary size: {vocab_size}")
print(itos)
# Re-executed to define words, vocab_size, stoi, and itos.

# STEP 2: DATASET SPLIT (TRAIN / DEV / TEST)

import random
import torch

random.seed(42)
random.shuffle(words)

block_size = 4 # context length

def build_dataset(words_list):
    X, Y = [], []
    for w in words_list:
        context = [0] * block_size
        for ch in w + '.':
            ix = stoi[ch]
            X.append(context)
            Y.append(ix)
            context = context[1:] + [ix] # crop and append
    return torch.tensor(X), torch.tensor(Y)

# split data: 80% train, 10% dev, 10% test
n1 = int(0.8 * len(words))
n2 = int(0.9 * len(words))

Xtr, Ytr = build_dataset(words[:n1])
Xdev, Ydev = build_dataset(words[n1:n2])
Xte, Yte = build_dataset(words[n2:])

print(f"Training set size: {Xtr.shape[0]} examples")
print(f"Dev set size: {Xdev.shape[0]} examples")
print(f"Test set size: {Xte.shape[0]} examples")

# STEP 3: MODEL INITIALIZATION
# optimal hyperparameters to prevent overfitting
emb_dim = 8
hidden_dim = 50

#initializing the model parameters with specified dimensions and random values using a torch.Generator for reproducibility
g = torch.Generator().manual_seed(2147483647)
C = torch.randn((vocab_size, emb_dim), generator=g)
W1 = torch.randn((block_size * emb_dim, hidden_dim), generator=g)
b1 = torch.randn(hidden_dim, generator=g)
W2 = torch.randn((hidden_dim, vocab_size), generator=g)
b2 = torch.randn(vocab_size, generator=g)

parameters = [C, W1, b1, W2, b2]
for p in parameters:
    p.requires_grad = True

print(f"Total model parameters: {sum(p.nelement() for p in parameters)}")
# Re-executed to define C, W1, b1, W2, b2, parameters.

# STEP 4: TRAINING LOOP
import torch
import torch.nn.functional as F

steps = 200000
batch_size = 32
lossi = []

print("Starting training...")
for i in range(steps):
    # minibatch construct
    ix = torch.randint(0, Xtr.shape[0], (batch_size,), generator=g)

    # forward pass
    emb = C[Xtr[ix]] # (batch_size, block_size, emb_dim: (32, 4, 8))
    h = torch.tanh(emb.view(-1, block_size * emb_dim) @ W1 + b1) # (batch_size, hidden_dim: (32,50))
    logits = h @ W2 + b2 # (batch_size, vocab_size: (32, 39))
    loss = F.cross_entropy(logits, Ytr[ix])

    # backward pass
    for p in parameters:
        p.grad = None
    loss.backward()

    # update
    lr = 0.05 if i < 100000 else 0.01
    for p in parameters:
        p.data -= lr * p.grad

    # track stats
    lossi.append(loss.log10().item())
    if i % 20000 == 0:
        print(f"Step {i:7d}/{steps} | Minibatch Loss: {loss.item():.4f}")
        # print the minibatch loss every 20,000 steps

print("Training completed!")

# STEP 5: QUALITY EVALUATION
@torch.no_grad()
def split_loss(split_name, X, Y):
    emb = C[X]
    h = torch.tanh(emb.view(-1, block_size * emb_dim) @ W1 + b1)
    logits = h @ W2 + b2
    loss = F.cross_entropy(logits, Y)
    print(f"Final {split_name} Loss: {loss.item():.4f}")

print("=== FINAL MODEL EVALUATION ===")
split_loss('Train', Xtr, Ytr)
split_loss('Dev  ', Xdev, Ydev)
split_loss('Test ', Xte, Yte)

# STEP 6: GENERATE SAMPLE NAMES
g = torch.Generator().manual_seed(2147483647 + 10)

print("=== Generated Portuguese Surnames ===")
for _ in range(40):
    out = []
    context = [0] * block_size
    while True:
      emb = C[torch.tensor([context])]
      h = torch.tanh(emb.view(1, -1) @ W1 + b1)
      logits = h @ W2 + b2
      probs = F.softmax(logits, dim=1)
      ix = torch.multinomial(probs, num_samples=1, generator=g).item()
      context = context[1:] + [ix]
      out.append(ix)
      if ix == 0:
        break

    print(''.join(itos[i] for i in out[:-1]))

# STEP 7: CROSS-LINGUAL EVALUATION (PT Model - ES Data)

# loading the Spanish dataset
words_es = requests.get("https://raw.githubusercontent.com/luizoquadros-lang/NLP_Surnames_predict/main/apellidos_es.txt").text.splitlines()
print(f"Loaded {len(words_es)} Spanish names.")


# evaluate Loss on Spanish Data
X_es, Y_es = [], []
skipped_es = 0

for w in words_es:
    # Spanish names rarely have characters outside the Portuguese vocab, but we keep this for safety.
    if any(ch not in stoi for ch in w):
        skipped_es += 1
        continue

    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X_es.append(context)
        Y_es.append(ix)
        context = context[1:] + [ix]

X_es = torch.tensor(X_es)
Y_es = torch.tensor(Y_es)

with torch.no_grad():
    emb = C[X_es]
    h = torch.tanh(emb.view(-1, block_size * emb.shape[2] if len(emb.shape)==3 else block_size * C.shape[1]) @ W1 + b1)
    logits = h @ W2 + b2
    loss_pt_on_es = F.cross_entropy(logits, Y_es)

print(f"\n=== EVALUATION RESULTS ===")
print(f"Portuguese Model Loss on ES Data: {loss_pt_on_es.item():.4f}")
print(f"(Evaluated on {X_es.shape[0]} character transitions. Skipped {skipped_es} names due to Out-of-Vocabulary characters.)")

# generate Spanish names to see the transfer quality
print("\n=== GENERATION: Portuguese Model trying to generate Spanish names ===")
g_sample = torch.Generator().manual_seed(2147483647 + 200)

for _ in range(40):
    out = []
    context = [0] * block_size
    while True:
        emb = C[torch.tensor([context])]
        h = torch.tanh(emb.view(1, -1) @ W1 + b1)
        logits = h @ W2 + b2
        probs = F.softmax(logits, dim=1)
        ix = torch.multinomial(probs, num_samples=1, generator=g_sample).item()
        context = context[1:] + [ix]
        out.append(ix)
        if ix == 0:
            break
    print(''.join(itos[i] for i in out[:-1]))
